### ISSUE TITLE
멀티 모니터를 사용할 때 주 모니터에만 창이 표시됨

### ISSUE THREAD

**Issue by hank-d** [hyeongyuan/duroot-desktop#2]
## 내용
보조모니터에서 상단 바의 아이콘을 클릭해도 주 모니터에 창이 표시됩니다 ㅎㅎ

## 버전
v0.2.2

## 재현경로
1. 듀얼 모니터 환경 구성
2. 보조 모니터에서 아이콘 클릭

**Comment by hyeongyuan** [comment]
[release-v0.2.6](https://github.com/hyeongyuan/duroot-desktop/releases/tag/release-0.2.6) 에서 수정되었습니다.

이슈 제보 감사합니다 👍
